### ISSUE TITLE
submitItem() doesn't correctly show name of contact

### ISSUE THREAD

**Issue by buneme** [klinker41/android-chips#13]
When using submitItem(name, number, imageURI) to add contacts to a RecipientEditTextView, the name of the contact is not shown on the chip, only their photo:
![image](https://cloud.githubusercontent.com/assets/3949246/8260918/8b03bac8-16be-11e5-9f5b-73d4fdde6a1d.png)

**Comment by LloydBlv** [comment]
Finally i figured it out, you should wait till the view settles itself down,and then call appropriate methods,so implement the call for addOnGlobalLayoutListener,and do your operations after that method being called!

**Comment by buneme** [comment]
Thanks, I'll try that and see if it works
