### ISSUE TITLE
Putting "comma" in does not create a "chip" for unknown contact just like android lollipop default SMS Android APP

### ISSUE THREAD

**Issue by dibakarece** [klinker41/android-chips#14]
first two chip I have selected from my suggesting list and add another contact 8697374578 using keyboard and putting next character , but 8697374578 does not create any chip for 8697374578.If I put space in state of " , " it create chip for that phone no.............please help me

**Comment by klinker24** [comment]
Same issue as this: https://github.com/klinker41/android-chips/issues/5

Will look into it soon, hopefully.
