### ISSUE TITLE
Where was this code taken from exactly?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [klinker41/android-chips#20]
I've searched in a lot of places, as I've made a similar library a long time ago:
https://github.com/AndroidDeveloperLB/ChipsLibrary

I'm just curious...

**Comment by klinker41** [comment]
https://android.googlesource.com/platform/frameworks/opt/chips/

**Comment by AndroidDeveloperLB** [comment]
Nice. Thank you. Would you mind adding this piece of information on the main page of the repo?
