### ISSUE TITLE
Permissions checking for Marshmallow

### ISSUE THREAD

**Issue by tyczj** [klinker41/android-chips#25]
Are there any plans to check for permissions for Marshmallow if not what would be the best way to disable pulling from the contacts provider? Would just not setting the adapter be sufficient?

**Comment by klinker41** [comment]
No, I don't plan on adding this to the library. It shouldn't be pulling any
information until you start typing.

**Comment by tyczj** [comment]
`It shouldn't be pulling any information until you start typing`

right but how can we stop it from pulling if they dont grant the permission?

**Comment by klinker41** [comment]
If they don't grant the permission then there's no reason to use this
library, it can't do anything.

**Comment by tyczj** [comment]
you can still input email address and stuff even if they are not in the contacts provider

**Comment by klinker41** [comment]
Feel free to create this functionality yourself if you need it and submit a
pull request, but I will continue to operate under the assumption that the
permissions have been granted, since that is the entire point of the
library.
