### ISSUE TITLE
New Chip without icon

### ISSUE THREAD

**Issue by pilootchoum** [klinker41/android-chips#30]
As I'm creating a new Chip based on a phone number on contact name, which is not matching any of the phone's contact's from the address book, the chip then does not have any icon setted,

Is that normal?

![droid screen-1](https://cloud.githubusercontent.com/assets/1533159/11444113/28948640-9523-11e5-95b6-54b300e780d3.png)

**Comment by pilootchoum** [comment]
I know it might not be implemented, maybe you could just lead me in the right direction to do it.

**Comment by Shusshu** [comment]
That means it is not part of your contact address book

**Comment by pilootchoum** [comment]
Thx Shusshu but I know what you just said, I even wrote it in my issue........

I'm trying to understand how to show the same default picture one the chip than the one showed when the contact exists in the addess book but with no picture setted.

**Comment by Shusshu** [comment]
Ok, my bad...

It shouldn't be hard to put the default icon too

**Comment by klinker24** [comment]
This is done with this PR: https://github.com/klinker41/android-chips/pull/49
