### ISSUE TITLE
submitItem not displaying contact photo

### ISSUE THREAD

**Issue by abidfs** [klinker41/android-chips#31]
Hi,
When I call submitItem(displayName, strMailId, Uri.parse(photoUri), photoBytes) on RecipientEditTextView, it does not display contact photo

**Comment by KtodaZ** [comment]
Hi, I had the same issue but fixed it by making sure my Uri was correct. In my case all I had to do was use a .trim() on its string value before parsing it. Hope this helps

**Comment by phamvansy** [comment]
try
RecipientEntry entry = RecipientEntry.constructGeneratedEntry(name,s,true);
phoneRetv.addRecipient(entry);
