### ISSUE TITLE
Is this lib still maintained?

### ISSUE THREAD

**Issue by Rainer-Lang** [klinker41/android-chips#34]

**Comment by timkoers** [comment]
I think it isn't. I might release a custom library with new functions. I'll update you soon (I hope)

**Comment by Rainer-Lang** [comment]
Would be cool ☺️

**Comment by Rainer-Lang** [comment]
@timkoers Any news? Is there an ETA?

**Comment by timkoers** [comment]
@Rainer-Lang I think I am not going to continue developing. I am sorry but the whole library is badly documented from the developers side of view and it's way to complicated to just use a String.

**Comment by Rainer-Lang** [comment]
@timkoers Yes I can understand this.... I will close this issue.
If you just start such a lib - please let me know. :)
