### ISSUE TITLE
'comma' does not create a new chip

### ISSUE THREAD

**Issue by shaggyarora94** [klinker41/android-chips#39]

**Comment by Ironthighs** [comment]
Comma works for me...though I'm not sure if that's because I added that functionality or what. You can try my fork (have had a PR out there for a couple months now...) if you want. 
https://github.com/Ironthighs/android-chips

**Comment by klinker24** [comment]
Same issue as this basically: https://github.com/klinker41/android-chips/issues/5

Will look into it soon hopefully.
