### ISSUE TITLE
Send DrawableRecipientChips[] to Another Activity

### ISSUE THREAD

**Issue by donniemceduns** [klinker41/android-chips#4]
I know this very very trivial. After geting all the chips with:

DrawableRecipientChips[] chips = phoneRetv.getSortedRecipients();

how do i send it to another activity?

I tried:

Intent intent = new Intent(this, editList.class);
        intent.putStringArrayListExtra("chips", DrawableRecipientChips[]);
        startActivity(intent)

But its not working. please help.

Btw,
Great Libary :dancers:

**Comment by cargo8** [comment]
DrawableRecipientChips are not Strings, so of course this does not work. You should probably iterate over the array to extract the relevant information (email or phone or whatever) and store an array of those elements passed to the next activity

**Comment by klinker24** [comment]
Sending the individual results is the way to go, yes. You shouldn't try to send a the object.
