### ISSUE TITLE
Custom adapter - is it possible yet?

### ISSUE THREAD

**Issue by Ab-Appletic** [klinker41/android-chips#42]
You said it wasn't possible, but if that was a year ago and I'd like to know if it has been added.

**Comment by klinker24** [comment]
No, I haven't added it, I would accept a pull request if you added it though.

Closing as duplicate: https://github.com/klinker41/android-chips/issues/26

**Comment by Ab-Appletic** [comment]
I'm not sure how to do it. Maybe one day :)
