### ISSUE TITLE
How can i set multiple contacts in Chip Edittext?

### ISSUE THREAD

**Issue by umangce** [klinker41/android-chips#9]
I want to implement application which provides option to user to select contacts. Once user close that application and restart it then that contacts should be appear in Chip Edittext.
I used "submitItem" method but it is not working at all.
So Is there a way to set multiple Contacts ?

**Comment by klinker41** [comment]
There is not a way to currently do this in the library. Please feel free to add it and send a pull request!

**Comment by umangce** [comment]
Okay. I will try. Thanks for your reply.

**Comment by Shusshu** [comment]
Adding this method to the class is sufficient:

```java
     public void addRecipients(RecipientEntry entry) {
         append(entry.getDisplayName());
         submitItem(entry);
     }
```
